//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.19.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../api-client';
import { useQuery, useMutation } from '@tanstack/react-query';
import type { UseQueryResult, QueryFunctionContext, UseQueryOptions, QueryClient, QueryKey, MutationKey, UseMutationOptions, UseMutationResult, QueryMeta, MutationMeta } from '@tanstack/react-query';
import { trimArrayEnd, isParameterObject, getBaseUrl, addMetaToOptions  } from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import * as Client from './ResultControllerClient'
export { Client };

export type ResultByBotIdResultControllerQueryParameters = {
  botId: string;
};

    
export function resultByBotIdUrl(botId: string): string {
  let url_ = getBaseUrl() + "/api/user/real-estate/results/{botId}";
if (botId === undefined || botId === null)
  throw new Error("The parameter 'botId' must be defined.");
url_ = url_.replace("{botId}", encodeURIComponent("" + botId));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let resultByBotIdDefaultOptions: UseQueryOptions<void, unknown, void> = {
  queryFn: __resultByBotId,
};
export function getResultByBotIdDefaultOptions(): UseQueryOptions<void, unknown, void> {
  return resultByBotIdDefaultOptions;
};
export function setResultByBotIdDefaultOptions(options: UseQueryOptions<void, unknown, void>) {
  resultByBotIdDefaultOptions = options;
}

export function resultByBotIdQueryKey(botId: string): QueryKey;
export function resultByBotIdQueryKey(...params: any[]): QueryKey {
  if (params.length === 1 && isParameterObject(params[0])) {
    const { botId,  } = params[0] as ResultByBotIdResultControllerQueryParameters;

    return trimArrayEnd([
        'ResultControllerClient',
        'resultByBotId',
        botId as any,
      ]);
  } else {
    return trimArrayEnd([
        'ResultControllerClient',
        'resultByBotId',
        ...params
      ]);
  }
}
function __resultByBotId(context: QueryFunctionContext) {
  return Client.resultByBotId(
      context.queryKey[2] as string    );
}

export function useResultByBotIdQuery<TSelectData = void, TError = unknown>(dto: ResultByBotIdResultControllerQueryParameters, options?: UseQueryOptions<void, TError, TSelectData>): UseQueryResult<TSelectData, TError>;

export function useResultByBotIdQuery<TSelectData = void, TError = unknown>(botId: string, options?: UseQueryOptions<void, TError, TSelectData>): UseQueryResult<TSelectData, TError>;
export function useResultByBotIdQuery<TSelectData = void, TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<void, TError, TSelectData> | undefined = undefined;
  let botId: any = undefined;
  
  if (params.length > 0) {
    if (isParameterObject(params[0])) {
      ({ botId,  } = params[0] as ResultByBotIdResultControllerQueryParameters);
      options = params[1];
    } else {
      [botId, options] = params;
    }
  }

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useQuery<void, TError, TSelectData>({
    queryFn: __resultByBotId,
    queryKey: resultByBotIdQueryKey(botId),
    ...resultByBotIdDefaultOptions as unknown as UseQueryOptions<void, TError, TSelectData>,
    ...options,
  });
}

export function setResultByBotIdData(queryClient: QueryClient, updater: (data: void | undefined) => void, botId: string) {
  queryClient.setQueryData(resultByBotIdQueryKey(botId),
    updater
  );
}

export function setResultByBotIdDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: void | undefined) => void) {
  queryClient.setQueryData(queryKey, updater);
}
    
    
export function updateUrl(id: number, botId: number): string {
  let url_ = getBaseUrl() + "/api/user/real-estate/results/{botId}/{id}";
if (id === undefined || id === null)
  throw new Error("The parameter 'id' must be defined.");
url_ = url_.replace("{id}", encodeURIComponent("" + id));
if (botId === undefined || botId === null)
  throw new Error("The parameter 'botId' must be defined.");
url_ = url_.replace("{botId}", encodeURIComponent("" + botId));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function updateMutationKey(id: number, botId: number): MutationKey {
  return trimArrayEnd([
      'ResultControllerClient',
      'update',
      id as any,
      botId as any,
    ]);
}

export function useUpdateMutation<TContext>(id: number, botId: number, options?: Omit<UseMutationOptions<void, unknown, void, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<void, unknown, void, TContext> {
  const key = updateMutationKey(id, botId);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
      return useMutation(() => Client.update(id, botId), {...options, mutationKey: key});
}